### ISSUE TITLE
Создать spring boot проект для телеграмм бота, реализовать эхо чат

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/marketplace#2]
https://github.com/oagafonov/TelegramBots

Создать новый spring boot проект в папке bot
Реализовать эхо-чат: бот должен отвечать пользователю полученным сообщением

**Comment by Ykr8891** [comment]
реализовано в https://github.com/Java-Java-Bootcamp/marketplace/pull/27/commits
