### ISSUE TITLE
telegrambot - Спроектировать логику взаимодействия пользователя с ботом в текстовом формате

### ISSUE THREAD

**Issue by slow3586** [Java-Java-Bootcamp/marketplace#24]
Необходимо в обычном текстовом файле указать какие запросы пользователь может отправлять боту и как он должен на них реагировать, т.е. спроектировать полную последовательность запросов от начала поиска до получения списка товаров и их дальнейшего просмотра. При проектировании учитывать будущую необходимость в сортировке и пагинации товаров.
Например:
1) Пользователь: Поиск
Бот: Введите критерий для поиска
2) Пользователь: "Критерий для поиска"
Бот: Выберите сортировку (меню)

**Comment by Ykr8891** [comment]
1. Пользователь инициализирует чат с ботом (вводит /start)

Сообщение для пользвоателя: Добро пожаловать! Нажмите "Поиск товаров" для поиска товаров.
Отображется кнопка Поиск товаров

2. Пользователь вводит /search (клик по кнопке "Поиск") и в поиск подставляется сортировка по рейтингу товара

Сообщение для пользвоателя: Напишите категорию, марку и характеристики товара

Пользователь вводит текст поискового запроса и ?жмёт enter?

Выведено 20 или меньше товаров. Если товаров =0, то выводится сообщение "По вашему запросу ничего не найдено"
В каждую строчку выдачи выходит следующая информация: информация о товаре (категория, производитель, марка характеристики, рейтинг), информация о продавце (наименование, рейтинг), цена товара, наличие (достаточно, если больше 5-ти или осталось N шт в противном случае). Список отсортирован по рейтингу товара.
Отображаются кнопки: Показать еще 20 товаров (если на следующей странице есть 20 товаров), Поиск товаров, Изменить сортировку

2.1
Пользователь вводит /changeSort (клик по кнопке "Изменить сортировку")
Сообщение для пользвоателя: Выберите тип сортировки
Отображются кнопки: По рейтингу товара, По рейтингу продавца, по стоимости
Пользователь вводит /search (клик по кнопке "Поиск") и в поиск подставляется сортировка по выбранному крмтерию

Выведено 20 или меньше товаров
В каждую строчку выдачи выходит следующая информация: информация о товаре (категория, производитель, марка характеристики, рейтинг), информация о продавце (наименование, рейтинг), цена товара, наличие (достаточно, если больше 5-ти или осталось N шт в противном случае). Список отсортирован по рейтингу товара.
Отображаются кнопки: Показать еще 20 товаров (если на следующей странице есть 20 товаров), Поиск товаров, Изменить сортировку

2.2
Пользователь вводит /nextPage (клик по кнопке "Показать еще 20 товаров")
Выводится следующий 20 или меньше товаров
Отображаются кнопки: Посмотреть еще 20 товаров (если на следующей странице есть 20 товаров), Поиск товаров, Изменить сортировку

2.3
Сообщение для пользвоателя: "По вашему запросу ничего не найдено"
Отображется кнопка Поиск товаров
