### ISSUE TITLE
Реализовать функцию заказа товара

### ISSUE THREAD

**Issue by sabinaIsm** [Java-Java-Bootcamp/marketplace#33]
1. Пользователь нажимает на кнопку "Заказать" понравившегося товара.
2. Бот запрашивает количество товара.
3. Пользователь вводит число.
4. Бот выводит информацию об оформляемом заказе с суммой заказа.

**Comment by AVPGenium** [comment]
+ проверка наличия нужного количества товара

**Comment by AVPGenium** [comment]
Уточнение по пункту 4:
- должно происходить UPDATE соответствующего cartItem
- после этого в боте происходит агрегация кол-во  * цену
