### ISSUE TITLE
Реализовать сохранение состояния корзины

### ISSUE THREAD

**Issue by sabinaIsm** [Java-Java-Bootcamp/marketplace#34]
Пользователь может "заказать" разные товары. До потверждения этот список должен храниться в памяти

**Comment by AVPGenium** [comment]
**Описание:**
Сохранение контекста пользователя с наполненной корзиной на бекенде

![marketplace-save-cart-seq](https://user-images.githubusercontent.com/4224817/163831397-5222655b-975c-4a92-b5a2-c625f9497597.png)
