### ISSUE TITLE
Разработать модель данных

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/marketplace#4]
Сущности:

Товар
- название
- производитель
- описание

Продавец:
- название
- рейтинг

Товары продавца
- продавец
- товар
- кол-во

Заполнить тестовыми данными 20-30 организаций
Заполнить тестовыми данными 20-30 товаров
Заполнить тестовыми данными 30-40 товаров продавцов

**Comment by evgnep** [comment]
Дополнительно нужны поля
* category: text
* model: text
*  rate: numeric
