### ISSUE TITLE
Реализовать обработку ботом текста поиска товаров

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/marketplace#6]
Пользователь вводит текст
Бот принимает текст и вызывает API GET /product-offers?text={text}
Полученный результат преобразует в ответ пользователю

**Comment by Ykr8891** [comment]
Запрос-ответ

GET /product-offers?text={text}

response: List Of ProductOffer

ProductOffer:
  product:
    category: text
    model: text
    manufacturer: text
    description: text
    rate: numeric
  store:
     name: text
     rate: numeric
  available: numeric

**Comment by Ykr8891** [comment]
Сделано в https://github.com/Java-Java-Bootcamp/marketplace/pull/41
