### ISSUE TITLE
Реализовать в API поиска выдачу товаров окнами

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/marketplace#7]
GET /product-offers?text={text}&limit={limit}&offset={offset}
limit - кол-во записей в ответе
offset - на какое кол-во нужно сдвинуться

например, limit = 10 offset=20 означает, что в ответ API попадет 10 записей начиная с 21.

**Comment by evgnep** [comment]
+ сервис

**Comment by evgnep** [comment]
@NickLarionov , если сделали - то сошлитесь на пулл-реквест. Иначе - уберите из ревью
