### ISSUE TITLE
Реализовать поддержку меню настройки сортировки результатов выдачи бота

### ISSUE THREAD

**Issue by oagafonov** [Java-Java-Bootcamp/marketplace#9]
У бота находящегося в состоянии поиска, должно быть меню, где можно выбрать варианты сортировки

- по рейтингу товара (product-rate)
- по рейтингу продавца (organization-rate)
- по стоимости (price)
После смены варианта сортировки, бот должен повторно запросить у API /product-offers данные указав вариант сортировки
Например
GET /product-offers?text={text}&order=price

**Comment by Ykr8891** [comment]
Сделано в https://github.com/Java-Java-Bootcamp/marketplace/pull/41

**Comment by Ykr8891** [comment]
https://github.com/Java-Java-Bootcamp/marketplace/pull/44
